const ADD_ITEM = "ADD_ITEM";
const REMOVE_ITEM = "REMOVE_ITEM";
const UPDATE_VALUE = "UPDATE_VALUE";
const CLICK_ITEMS = "CLICK_ITEMS";


export {
    ADD_ITEM,
    REMOVE_ITEM,
    UPDATE_VALUE,
    CLICK_ITEMS
}